apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherface
  labels:
    app: etherface
    component: etherface
spec:
  replicas: 0

  selector:
    matchLabels:
      app: etherface
      component: etherface
  template:
    metadata:
      labels:
        app: etherface
        component: etherface
    spec:
      serviceAccountName: etherface
      containers:
        - name: etherface
          image: rss3/etherface
          imagePullPolicy: IfNotPresent
          command: ["etherface"]
          envFrom:
            - secretRef:
                name: etherface
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
