apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etherface
  labels:
    app: etherface
    component: etherface
spec:
  serviceName: "etherface"
  selector:
    matchLabels:
      app: etherface
      component: etherface
  template:
    metadata:
      labels:
        app: etherface
        component: etherface
    spec:
      serviceAccountName: etherface
      containers:
        - name: etherface
          image: rss3/etherface
          imagePullPolicy: IfNotPresent
          command: ["etherface"]
          envFrom:
            - secretRef:
                name: etherface
          env:
            - name: VAULT_ADDR
              value: "http://vault-ui.guardian.svc.cluster.local:8200"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
