apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherface-rest
  labels:
    app: etherface
    component: rest
spec:
  selector:
    matchLabels:
      app: etherface
      component: rest
  template:
    metadata:
      labels:
        app: etherface
        component: rest
    spec:
      serviceAccountName: etherface
      containers:
        - name: etherface
          image: rss3/etherface
          imagePullPolicy: IfNotPresent
          command: ["etherface-rest"]
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: etherface
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
