apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ui
  - rest
  - etherface

images:
  - name: rss3/etherface-ui
    newName: rss3/etherface-ui
    newTag: 4f575741d89ef20df9808419e5c828dc2b4e8954
