apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ui
  - rest
  - etherface

images:
  - name: rss3/etherface-ui
    newName: rss3/etherface-ui
    newTag: 9396d529b8ead6e37e5994e341cbcfb825e942a3
  - name: rss3/etherface
    newName: rss3/etherface
    newTag: 9396d529b8ead6e37e5994e341cbcfb825e942a3
